### ISSUE TITLE
Possible to replace JavaScriptSerializer with .NET Core friendly framework?

### ISSUE THREAD

**Issue by GeorgeS2019** [fel88/Dagre.NET#3]
JavaScriptSerializer  from System.Web.Script.Serialization (System.Web.Extension) is limited for only .NET Framework

I have examined Dagre.NET, the only class preventing porting to e.g. .NET6 is JavaScriptSerializer  

[Is there an option to replace the use of JavaScriptSerializer  in  Dagre.NET](https://stackoverflow.com/questions/54110411/javascriptserializer-is-not-allowed-in-net-core-project)?

Potential relevant links
- [How do I use JavaScriptSerializer in ASP.NET 5?](https://de.coredump.biz/questions/30239683/how-do-i-use-javascriptserializer-in-aspnet-5)
- [ASP.Net vnext5 - cannot find JavaScriptSerializer](https://forums.asp.net/t/2050853.aspx?ASP+Net+vnext5+cannot+find+JavaScriptSerializer)

**Comment by fel88** [comment]
@GeorgeS2019 Hmm, strange. Dagre.NET is .Net Standard 2.0, besides it doesn't contains references to the JavaScriptSerializer

![image](https://user-images.githubusercontent.com/15663687/135915229-4309c0a2-7517-4d50-b94b-b1c27887e321.png)

**Comment by GeorgeS2019** [comment]
@fel88  It was my mistake :-)

I was checking [DagrePort](https://github.com/fel88/Dendrite/blob/dagre-debug/DagrePort/DagrePort.csproj)

**Comment by GeorgeS2019** [comment]
@fel88  These [Unit Tests]( https://github.com/fel88/Dendrite/blob/dagre-debug/DagrePort/DagreTester.cs) are valuable for Dagre.NET.UnitTests project.  Do you have plan to bring them to this new project [ Dagre.NET.UnitTests}?
